/*
 * This file is generated by jOOQ.
 */
package BookingApp2.com.example.demo.entities.tables.records;


import BookingApp2.com.example.demo.entities.tables.Property;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PropertyRecord extends UpdatableRecordImpl<PropertyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>booking_app.property.PropertyId</code>.
     */
    public PropertyRecord setPropertyid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.PropertyId</code>.
     */
    public Integer getPropertyid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>booking_app.property.AirportTransfer</code>.
     */
    public PropertyRecord setAirporttransfer(Boolean value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.AirportTransfer</code>.
     */
    public Boolean getAirporttransfer() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>booking_app.property.Availability</code>.
     */
    public PropertyRecord setAvailability(Boolean value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.Availability</code>.
     */
    public Boolean getAvailability() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>booking_app.property.Balcony</code>.
     */
    public PropertyRecord setBalcony(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.Balcony</code>.
     */
    public String getBalcony() {
        return (String) get(3);
    }

    /**
     * Setter for <code>booking_app.property.Bar</code>.
     */
    public PropertyRecord setBar(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.Bar</code>.
     */
    public Boolean getBar() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>booking_app.property.Bathroom</code>.
     */
    public PropertyRecord setBathroom(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.Bathroom</code>.
     */
    public String getBathroom() {
        return (String) get(5);
    }

    /**
     * Setter for <code>booking_app.property.Bedroom</code>.
     */
    public PropertyRecord setBedroom(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.Bedroom</code>.
     */
    public String getBedroom() {
        return (String) get(6);
    }

    /**
     * Setter for <code>booking_app.property.ChildFriendly</code>.
     */
    public PropertyRecord setChildfriendly(Boolean value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.ChildFriendly</code>.
     */
    public Boolean getChildfriendly() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>booking_app.property.City</code>.
     */
    public PropertyRecord setCity(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.City</code>.
     */
    public String getCity() {
        return (String) get(8);
    }

    /**
     * Setter for <code>booking_app.property.Country</code>.
     */
    public PropertyRecord setCountry(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.Country</code>.
     */
    public String getCountry() {
        return (String) get(9);
    }

    /**
     * Setter for <code>booking_app.property.County</code>.
     */
    public PropertyRecord setCounty(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.County</code>.
     */
    public String getCounty() {
        return (String) get(10);
    }

    /**
     * Setter for <code>booking_app.property.Description</code>.
     */
    public PropertyRecord setDescription(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.Description</code>.
     */
    public String getDescription() {
        return (String) get(11);
    }

    /**
     * Setter for <code>booking_app.property.Dimension</code>.
     */
    public PropertyRecord setDimension(Double value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.Dimension</code>.
     */
    public Double getDimension() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>booking_app.property.GuestNumber</code>.
     */
    public PropertyRecord setGuestnumber(Integer value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.GuestNumber</code>.
     */
    public Integer getGuestnumber() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>booking_app.property.Kitchen</code>.
     */
    public PropertyRecord setKitchen(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.Kitchen</code>.
     */
    public String getKitchen() {
        return (String) get(14);
    }

    /**
     * Setter for <code>booking_app.property.LivingRoom</code>.
     */
    public PropertyRecord setLivingroom(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.LivingRoom</code>.
     */
    public String getLivingroom() {
        return (String) get(15);
    }

    /**
     * Setter for <code>booking_app.property.Name</code>.
     */
    public PropertyRecord setName(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.Name</code>.
     */
    public String getName() {
        return (String) get(16);
    }

    /**
     * Setter for <code>booking_app.property.Parking</code>.
     */
    public PropertyRecord setParking(Boolean value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.Parking</code>.
     */
    public Boolean getParking() {
        return (Boolean) get(17);
    }

    /**
     * Setter for <code>booking_app.property.PetFriendly</code>.
     */
    public PropertyRecord setPetfriendly(Boolean value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.PetFriendly</code>.
     */
    public Boolean getPetfriendly() {
        return (Boolean) get(18);
    }

    /**
     * Setter for <code>booking_app.property.Picture</code>.
     */
    public PropertyRecord setPicture(String value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.Picture</code>.
     */
    public String getPicture() {
        return (String) get(19);
    }

    /**
     * Setter for <code>booking_app.property.Price</code>.
     */
    public PropertyRecord setPrice(Double value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.Price</code>.
     */
    public Double getPrice() {
        return (Double) get(20);
    }

    /**
     * Setter for <code>booking_app.property.Rating</code>.
     */
    public PropertyRecord setRating(Integer value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.Rating</code>.
     */
    public Integer getRating() {
        return (Integer) get(21);
    }

    /**
     * Setter for <code>booking_app.property.Sauna</code>.
     */
    public PropertyRecord setSauna(Boolean value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.Sauna</code>.
     */
    public Boolean getSauna() {
        return (Boolean) get(22);
    }

    /**
     * Setter for <code>booking_app.property.Smoking</code>.
     */
    public PropertyRecord setSmoking(Boolean value) {
        set(23, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.Smoking</code>.
     */
    public Boolean getSmoking() {
        return (Boolean) get(23);
    }

    /**
     * Setter for <code>booking_app.property.Spa</code>.
     */
    public PropertyRecord setSpa(Boolean value) {
        set(24, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.Spa</code>.
     */
    public Boolean getSpa() {
        return (Boolean) get(24);
    }

    /**
     * Setter for <code>booking_app.property.Terrace</code>.
     */
    public PropertyRecord setTerrace(String value) {
        set(25, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.Terrace</code>.
     */
    public String getTerrace() {
        return (String) get(25);
    }

    /**
     * Setter for <code>booking_app.property.Type</code>.
     */
    public PropertyRecord setType(String value) {
        set(26, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.Type</code>.
     */
    public String getType() {
        return (String) get(26);
    }

    /**
     * Setter for <code>booking_app.property.Wifi</code>.
     */
    public PropertyRecord setWifi(Boolean value) {
        set(27, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property.Wifi</code>.
     */
    public Boolean getWifi() {
        return (Boolean) get(27);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PropertyRecord
     */
    public PropertyRecord() {
        super(Property.PROPERTY);
    }

    /**
     * Create a detached, initialised PropertyRecord
     */
    public PropertyRecord(Integer propertyid, Boolean airporttransfer, Boolean availability, String balcony, Boolean bar, String bathroom, String bedroom, Boolean childfriendly, String city, String country, String county, String description, Double dimension, Integer guestnumber, String kitchen, String livingroom, String name, Boolean parking, Boolean petfriendly, String picture, Double price, Integer rating, Boolean sauna, Boolean smoking, Boolean spa, String terrace, String type, Boolean wifi) {
        super(Property.PROPERTY);

        setPropertyid(propertyid);
        setAirporttransfer(airporttransfer);
        setAvailability(availability);
        setBalcony(balcony);
        setBar(bar);
        setBathroom(bathroom);
        setBedroom(bedroom);
        setChildfriendly(childfriendly);
        setCity(city);
        setCountry(country);
        setCounty(county);
        setDescription(description);
        setDimension(dimension);
        setGuestnumber(guestnumber);
        setKitchen(kitchen);
        setLivingroom(livingroom);
        setName(name);
        setParking(parking);
        setPetfriendly(petfriendly);
        setPicture(picture);
        setPrice(price);
        setRating(rating);
        setSauna(sauna);
        setSmoking(smoking);
        setSpa(spa);
        setTerrace(terrace);
        setType(type);
        setWifi(wifi);
    }

    /**
     * Create a detached, initialised PropertyRecord
     */
    public PropertyRecord(BookingApp2.com.example.demo.entities.tables.pojos.Property value) {
        super(Property.PROPERTY);

        if (value != null) {
            setPropertyid(value.getPropertyid());
            setAirporttransfer(value.getAirporttransfer());
            setAvailability(value.getAvailability());
            setBalcony(value.getBalcony());
            setBar(value.getBar());
            setBathroom(value.getBathroom());
            setBedroom(value.getBedroom());
            setChildfriendly(value.getChildfriendly());
            setCity(value.getCity());
            setCountry(value.getCountry());
            setCounty(value.getCounty());
            setDescription(value.getDescription());
            setDimension(value.getDimension());
            setGuestnumber(value.getGuestnumber());
            setKitchen(value.getKitchen());
            setLivingroom(value.getLivingroom());
            setName(value.getName());
            setParking(value.getParking());
            setPetfriendly(value.getPetfriendly());
            setPicture(value.getPicture());
            setPrice(value.getPrice());
            setRating(value.getRating());
            setSauna(value.getSauna());
            setSmoking(value.getSmoking());
            setSpa(value.getSpa());
            setTerrace(value.getTerrace());
            setType(value.getType());
            setWifi(value.getWifi());
        }
    }
}
