/*
 * This file is generated by jOOQ.
 */
package BookingApp2.com.example.demo.entities.tables.records;


import BookingApp2.com.example.demo.entities.tables.PropertyReviews;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PropertyReviewsRecord extends UpdatableRecordImpl<PropertyReviewsRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>booking_app.property_reviews.PropertyId</code>.
     */
    public PropertyReviewsRecord setPropertyid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property_reviews.PropertyId</code>.
     */
    public Integer getPropertyid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>booking_app.property_reviews.ReviewId</code>.
     */
    public PropertyReviewsRecord setReviewid(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.property_reviews.ReviewId</code>.
     */
    public Integer getReviewid() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PropertyReviews.PROPERTY_REVIEWS.PROPERTYID;
    }

    @Override
    public Field<Integer> field2() {
        return PropertyReviews.PROPERTY_REVIEWS.REVIEWID;
    }

    @Override
    public Integer component1() {
        return getPropertyid();
    }

    @Override
    public Integer component2() {
        return getReviewid();
    }

    @Override
    public Integer value1() {
        return getPropertyid();
    }

    @Override
    public Integer value2() {
        return getReviewid();
    }

    @Override
    public PropertyReviewsRecord value1(Integer value) {
        setPropertyid(value);
        return this;
    }

    @Override
    public PropertyReviewsRecord value2(Integer value) {
        setReviewid(value);
        return this;
    }

    @Override
    public PropertyReviewsRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PropertyReviewsRecord
     */
    public PropertyReviewsRecord() {
        super(PropertyReviews.PROPERTY_REVIEWS);
    }

    /**
     * Create a detached, initialised PropertyReviewsRecord
     */
    public PropertyReviewsRecord(Integer propertyid, Integer reviewid) {
        super(PropertyReviews.PROPERTY_REVIEWS);

        setPropertyid(propertyid);
        setReviewid(reviewid);
    }

    /**
     * Create a detached, initialised PropertyReviewsRecord
     */
    public PropertyReviewsRecord(BookingApp2.com.example.demo.entities.tables.pojos.PropertyReviews value) {
        super(PropertyReviews.PROPERTY_REVIEWS);

        if (value != null) {
            setPropertyid(value.getPropertyid());
            setReviewid(value.getReviewid());
        }
    }
}
