/*
 * This file is generated by jOOQ.
 */
package BookingApp2.com.example.demo.entities.tables.records;


import BookingApp2.com.example.demo.entities.tables.Review;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReviewRecord extends UpdatableRecordImpl<ReviewRecord> implements Record5<Integer, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>booking_app.review.ReviewId</code>.
     */
    public ReviewRecord setReviewid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.review.ReviewId</code>.
     */
    public Integer getReviewid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>booking_app.review.Country</code>.
     */
    public ReviewRecord setCountry(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.review.Country</code>.
     */
    public String getCountry() {
        return (String) get(1);
    }

    /**
     * Setter for <code>booking_app.review.Description</code>.
     */
    public ReviewRecord setDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.review.Description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>booking_app.review.Icon</code>.
     */
    public ReviewRecord setIcon(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.review.Icon</code>.
     */
    public String getIcon() {
        return (String) get(3);
    }

    /**
     * Setter for <code>booking_app.review.Username</code>.
     */
    public ReviewRecord setUsername(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>booking_app.review.Username</code>.
     */
    public String getUsername() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Review.REVIEW.REVIEWID;
    }

    @Override
    public Field<String> field2() {
        return Review.REVIEW.COUNTRY;
    }

    @Override
    public Field<String> field3() {
        return Review.REVIEW.DESCRIPTION;
    }

    @Override
    public Field<String> field4() {
        return Review.REVIEW.ICON;
    }

    @Override
    public Field<String> field5() {
        return Review.REVIEW.USERNAME;
    }

    @Override
    public Integer component1() {
        return getReviewid();
    }

    @Override
    public String component2() {
        return getCountry();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public String component4() {
        return getIcon();
    }

    @Override
    public String component5() {
        return getUsername();
    }

    @Override
    public Integer value1() {
        return getReviewid();
    }

    @Override
    public String value2() {
        return getCountry();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public String value4() {
        return getIcon();
    }

    @Override
    public String value5() {
        return getUsername();
    }

    @Override
    public ReviewRecord value1(Integer value) {
        setReviewid(value);
        return this;
    }

    @Override
    public ReviewRecord value2(String value) {
        setCountry(value);
        return this;
    }

    @Override
    public ReviewRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ReviewRecord value4(String value) {
        setIcon(value);
        return this;
    }

    @Override
    public ReviewRecord value5(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public ReviewRecord values(Integer value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReviewRecord
     */
    public ReviewRecord() {
        super(Review.REVIEW);
    }

    /**
     * Create a detached, initialised ReviewRecord
     */
    public ReviewRecord(Integer reviewid, String country, String description, String icon, String username) {
        super(Review.REVIEW);

        setReviewid(reviewid);
        setCountry(country);
        setDescription(description);
        setIcon(icon);
        setUsername(username);
    }

    /**
     * Create a detached, initialised ReviewRecord
     */
    public ReviewRecord(BookingApp2.com.example.demo.entities.tables.pojos.Review value) {
        super(Review.REVIEW);

        if (value != null) {
            setReviewid(value.getReviewid());
            setCountry(value.getCountry());
            setDescription(value.getDescription());
            setIcon(value.getIcon());
            setUsername(value.getUsername());
        }
    }
}
