/*
 * This file is generated by jOOQ.
 */
package BookingApp2.com.example.demo.entities.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PropertyReviews implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer propertyid;
    private Integer reviewid;

    public PropertyReviews() {}

    public PropertyReviews(PropertyReviews value) {
        this.propertyid = value.propertyid;
        this.reviewid = value.reviewid;
    }

    public PropertyReviews(
        Integer propertyid,
        Integer reviewid
    ) {
        this.propertyid = propertyid;
        this.reviewid = reviewid;
    }

    /**
     * Getter for <code>booking_app.property_reviews.PropertyId</code>.
     */
    public Integer getPropertyid() {
        return this.propertyid;
    }

    /**
     * Setter for <code>booking_app.property_reviews.PropertyId</code>.
     */
    public PropertyReviews setPropertyid(Integer propertyid) {
        this.propertyid = propertyid;
        return this;
    }

    /**
     * Getter for <code>booking_app.property_reviews.ReviewId</code>.
     */
    public Integer getReviewid() {
        return this.reviewid;
    }

    /**
     * Setter for <code>booking_app.property_reviews.ReviewId</code>.
     */
    public PropertyReviews setReviewid(Integer reviewid) {
        this.reviewid = reviewid;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PropertyReviews other = (PropertyReviews) obj;
        if (propertyid == null) {
            if (other.propertyid != null)
                return false;
        }
        else if (!propertyid.equals(other.propertyid))
            return false;
        if (reviewid == null) {
            if (other.reviewid != null)
                return false;
        }
        else if (!reviewid.equals(other.reviewid))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.propertyid == null) ? 0 : this.propertyid.hashCode());
        result = prime * result + ((this.reviewid == null) ? 0 : this.reviewid.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PropertyReviews (");

        sb.append(propertyid);
        sb.append(", ").append(reviewid);

        sb.append(")");
        return sb.toString();
    }
}
