/*
 * This file is generated by jOOQ.
 */
package BookingApp2.com.example.demo.entities.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Review implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer reviewid;
    private String  country;
    private String  description;
    private String  icon;
    private String  username;

    public Review() {}

    public Review(Review value) {
        this.reviewid = value.reviewid;
        this.country = value.country;
        this.description = value.description;
        this.icon = value.icon;
        this.username = value.username;
    }

    public Review(
        Integer reviewid,
        String  country,
        String  description,
        String  icon,
        String  username
    ) {
        this.reviewid = reviewid;
        this.country = country;
        this.description = description;
        this.icon = icon;
        this.username = username;
    }

    /**
     * Getter for <code>booking_app.review.ReviewId</code>.
     */
    public Integer getReviewid() {
        return this.reviewid;
    }

    /**
     * Setter for <code>booking_app.review.ReviewId</code>.
     */
    public Review setReviewid(Integer reviewid) {
        this.reviewid = reviewid;
        return this;
    }

    /**
     * Getter for <code>booking_app.review.Country</code>.
     */
    public String getCountry() {
        return this.country;
    }

    /**
     * Setter for <code>booking_app.review.Country</code>.
     */
    public Review setCountry(String country) {
        this.country = country;
        return this;
    }

    /**
     * Getter for <code>booking_app.review.Description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>booking_app.review.Description</code>.
     */
    public Review setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Getter for <code>booking_app.review.Icon</code>.
     */
    public String getIcon() {
        return this.icon;
    }

    /**
     * Setter for <code>booking_app.review.Icon</code>.
     */
    public Review setIcon(String icon) {
        this.icon = icon;
        return this;
    }

    /**
     * Getter for <code>booking_app.review.Username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>booking_app.review.Username</code>.
     */
    public Review setUsername(String username) {
        this.username = username;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Review other = (Review) obj;
        if (reviewid == null) {
            if (other.reviewid != null)
                return false;
        }
        else if (!reviewid.equals(other.reviewid))
            return false;
        if (country == null) {
            if (other.country != null)
                return false;
        }
        else if (!country.equals(other.country))
            return false;
        if (description == null) {
            if (other.description != null)
                return false;
        }
        else if (!description.equals(other.description))
            return false;
        if (icon == null) {
            if (other.icon != null)
                return false;
        }
        else if (!icon.equals(other.icon))
            return false;
        if (username == null) {
            if (other.username != null)
                return false;
        }
        else if (!username.equals(other.username))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.reviewid == null) ? 0 : this.reviewid.hashCode());
        result = prime * result + ((this.country == null) ? 0 : this.country.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.icon == null) ? 0 : this.icon.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Review (");

        sb.append(reviewid);
        sb.append(", ").append(country);
        sb.append(", ").append(description);
        sb.append(", ").append(icon);
        sb.append(", ").append(username);

        sb.append(")");
        return sb.toString();
    }
}
