/*
 * This file is generated by jOOQ.
 */
package BookingApp2.com.example.demo.entities;


import BookingApp2.com.example.demo.entities.tables.Property;
import BookingApp2.com.example.demo.entities.tables.PropertyReviews;
import BookingApp2.com.example.demo.entities.tables.Review;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookingApp extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>booking_app</code>
     */
    public static final BookingApp BOOKING_APP = new BookingApp();

    /**
     * The table <code>booking_app.property</code>.
     */
    public final Property PROPERTY = Property.PROPERTY;

    /**
     * The table <code>booking_app.property_reviews</code>.
     */
    public final PropertyReviews PROPERTY_REVIEWS = PropertyReviews.PROPERTY_REVIEWS;

    /**
     * The table <code>booking_app.review</code>.
     */
    public final Review REVIEW = Review.REVIEW;

    /**
     * No further instances allowed
     */
    private BookingApp() {
        super("booking_app", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Property.PROPERTY,
            PropertyReviews.PROPERTY_REVIEWS,
            Review.REVIEW
        );
    }
}
