/*
 * This file is generated by jOOQ.
 */
package BookingApp2.com.example.demo.entities;


import BookingApp2.com.example.demo.entities.tables.PropertyReviews;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in booking_app.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PROPERTY_REVIEWS_REVIEWID_IDX = Internal.createIndex(DSL.name("ReviewId_idx"), PropertyReviews.PROPERTY_REVIEWS, new OrderField[] { PropertyReviews.PROPERTY_REVIEWS.REVIEWID }, false);
}
