/*
 * This file is generated by jOOQ.
 */
package BookingApp2.com.example.demo.entities;


import BookingApp2.com.example.demo.entities.tables.Property;
import BookingApp2.com.example.demo.entities.tables.PropertyReviews;
import BookingApp2.com.example.demo.entities.tables.Review;


/**
 * Convenience access to all tables in booking_app.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>booking_app.property</code>.
     */
    public static final Property PROPERTY = Property.PROPERTY;

    /**
     * The table <code>booking_app.property_reviews</code>.
     */
    public static final PropertyReviews PROPERTY_REVIEWS = PropertyReviews.PROPERTY_REVIEWS;

    /**
     * The table <code>booking_app.review</code>.
     */
    public static final Review REVIEW = Review.REVIEW;
}
